# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(239, 360)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 241, 61))
        self.label.setStyleSheet("QLabel{\n"
"font: 18pt \".AppleSystemUIFont\";\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 60, 61, 61))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(204, 204, 204);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 60, 61, 61))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(204, 204, 204);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 120, 61, 61))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(254, 204, 102);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 60, 61, 61))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-color: rgb(204, 204, 204);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 120, 61, 61))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-color: rgb(254, 204, 102);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(120, 120, 61, 61))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color: rgb(254, 204, 102);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(180, 60, 61, 61))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-color: rgb(204, 204, 204);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(180, 120, 61, 61))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background-color: rgb(204, 204, 204);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 180, 61, 61))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"background-color: rgb(254, 204, 102);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(60, 180, 61, 61))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"background-color: rgb(254, 204, 102);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(120, 180, 61, 61))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"background-color: rgb(254, 204, 102);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(180, 180, 61, 61))
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"background-color: rgb(204, 204, 204);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(0, 240, 61, 61))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"background-color: rgb(254, 204, 102);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(60, 240, 61, 61))
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"background-color: rgb(254, 204, 102);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(120, 240, 61, 61))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"background-color: rgb(254, 204, 102);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(180, 240, 61, 61))
        self.pushButton_19.setStyleSheet("QPushButton{\n"
"background-color: rgb(204, 204, 204);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(0, 300, 121, 61))
        self.pushButton_20.setStyleSheet("QPushButton{\n"
"background-color: rgb(254, 204, 102);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(120, 300, 61, 61))
        self.pushButton_21.setStyleSheet("QPushButton{\n"
"background-color: rgb(204, 204, 204);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(180, 300, 61, 61))
        self.pushButton_22.setStyleSheet("QPushButton{\n"
"background-color: rgb(204, 204, 204);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(127, 127, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_22.setObjectName("pushButton_22")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "0"))
        self.pushButton.setText(_translate("MainWindow", "C"))
        self.pushButton_2.setText(_translate("MainWindow", "+/-"))
        self.pushButton_3.setText(_translate("MainWindow", "7"))
        self.pushButton_4.setText(_translate("MainWindow", "%"))
        self.pushButton_5.setText(_translate("MainWindow", "8"))
        self.pushButton_6.setText(_translate("MainWindow", "9"))
        self.pushButton_7.setText(_translate("MainWindow", "/"))
        self.pushButton_8.setText(_translate("MainWindow", "x"))
        self.pushButton_9.setText(_translate("MainWindow", "4"))
        self.pushButton_10.setText(_translate("MainWindow", "5"))
        self.pushButton_11.setText(_translate("MainWindow", "6"))
        self.pushButton_16.setText(_translate("MainWindow", "-"))
        self.pushButton_13.setText(_translate("MainWindow", "1"))
        self.pushButton_14.setText(_translate("MainWindow", "2"))
        self.pushButton_15.setText(_translate("MainWindow", "3"))
        self.pushButton_19.setText(_translate("MainWindow", "+"))
        self.pushButton_20.setText(_translate("MainWindow", "0"))
        self.pushButton_21.setText(_translate("MainWindow", "."))
        self.pushButton_22.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
